### ISSUE TITLE
The text on this screen needs to be changed since there is no negative review from a customer

### ISSUE THREAD

**Issue by aarthyadityan** [inkdlab/writing-game-week3#18]
<img width="1204" alt="2017-01-19 05 20 58 pm" src="https://cloud.githubusercontent.com/assets/21074048/22127860/d766ffe4-de6b-11e6-9e7a-9fe81b0ddbc6.png">

**Comment by JSmith92** [comment]
Here is the new text update I gave it. Still need lori's review, so i'll leave this issue open.

![screen shot 2017-01-20 at 10 12 11 am](https://cloud.githubusercontent.com/assets/22644654/22154305/fd6d3022-def8-11e6-81fd-714c69dd558f.png)

**Comment by loristokes** [comment]
Hello and welcome to the Writing Game! Here you will learn how to write a professional, properly formatted business memo.
