### ISSUE TITLE
Add old desktop form and css in advance assessment

### ISSUE THREAD

**Issue by motwaniy** [inkdlab/writing-game-week3#2]
Add old desktop form and css instead of the current form in advance assessment. Display it in right side where the current form is placed. 
@tiagodcosta can you do this?

**Comment by JSmith92** [comment]
Put the memo notes and the input form within the same container. Make that container have the css of the desktop.

![screen shot 2017-01-19 at 2 13 24 pm](https://cloud.githubusercontent.com/assets/22644654/22121728/1c8d409c-de53-11e6-9b0a-e4ff8cc1923c.png)

Make it fit with in that container... if it is possible.

**Comment by tiagodcosta** [comment]
Fixed with 2b0a6e0777c2e4bee121bf7dda4e61e18ba6abc7
