### ISSUE TITLE
Advanced "Done" click

### ISSUE THREAD

**Issue by loristokes** [inkdlab/writing-game-week3#24]
I filled in all the blanks but when I click Done I get an error message saying fill in all the blanks.

**Comment by JSmith92** [comment]
I am not getting this problem. Can you send a screen shot of this? Also make sure to fill the To:, From:, and Subject:, with text along with the boxes.

**Comment by loristokes** [comment]
![screen shot 2017-01-20 at 2 35 17 pm](https://cloud.githubusercontent.com/assets/24571312/22162695/b353af32-df1d-11e6-9c93-76572b6d6e91.png)

**Comment by JSmith92** [comment]
Yes, your "To:" and "From:" fields are empty.  Try putting text within them and let me know if you're still getting that message.
