### ISSUE TITLE
Intermediate assemble the memo - body

### ISSUE THREAD

**Issue by loristokes** [inkdlab/writing-game-week3#28]
Indent the bulleted lists

**Comment by JSmith92** [comment]
@aarthyadityan @tiagodcosta Can you give this a try? I tied putting this code: <p style = 'text-indent: 20px;'>xxx</p>  and wrapping it around the Body's bullet points, but it only indents the first line. Can you see what it need?

**Comment by aarthyadityan** [comment]
Sure I can work on it

**Comment by JSmith92** [comment]
thanks

**Comment by aarthyadityan** [comment]
@loristokes, should we indent the bullets in beginner too?

**Comment by JSmith92** [comment]
Yes. Please do those too.
