### ISSUE TITLE
Advanced write the memo - bullets

### ISSUE THREAD

**Issue by loristokes** [inkdlab/writing-game-week3#29]
We have to be able to have bullets in the body, as we've drilled into students throughout the game.

**Comment by JSmith92** [comment]
@aarthyadityan @tiagodcosta @motwaniy Is there a way to get a widget within the game to create bullets for the input boxes?

**Comment by aarthyadityan** [comment]
Working on creating a button for this, see my comment on Issue #30

**Comment by aarthyadityan** [comment]
Added a button for toggling bullets (for the selected text or the current line). @tiagodcosta @JSmith92  @motwaniy, can you add some css to the button?

**Comment by JSmith92** [comment]
Css was added
