### ISSUE TITLE
PC-Chrome res 1366x768 Intermediate drag and drop

### ISSUE THREAD

**Issue by JSmith92** [inkdlab/writing-game-week3#33]
Bottom Text box is cut off at this resolution
![dnd pc](https://cloud.githubusercontent.com/assets/22644654/22219549/29b6c4d6-e179-11e6-8d90-f1834c27d986.png)

**Comment by JSmith92** [comment]
@aarthyadityan @tiagodcosta Should we give this scroll just to be safe?

**Comment by tiagodcosta** [comment]
@JSmith92 The drag and drop already has overflow auto. It's something on the media queries.

**Comment by JSmith92** [comment]
Its better, but still kind of cut off. 

![dnd pc](https://cloud.githubusercontent.com/assets/22644654/22223004/3387ff3a-e187-11e6-9358-334e7dc3efe8.png)
