### ISSUE TITLE
Intermediate, Delete third options from specific Questions

### ISSUE THREAD

**Issue by JSmith92** [inkdlab/writing-game-week3#4]
In Intermediate drag-and drop, their are questions that only give you 2 options.. Delete the third option that doesn't have content.

![screen shot 2017-01-19 at 2 00 01 pm](https://cloud.githubusercontent.com/assets/22644654/22121018/304a0884-de50-11e6-9ab9-49f39bc8cbe2.png)

**Comment by aarthyadityan** [comment]
Working on this
