### ISSUE TITLE
Modify css for help references to round all corners

### ISSUE THREAD

**Issue by aarthyadityan** [inkdlab/writing-game-week3#6]
<img width="568" alt="2017-01-19 02 20 13 pm" src="https://cloud.githubusercontent.com/assets/21074048/22121528/7bdf7ed0-de52-11e6-8172-3da2a925a256.png">

'.modal__menu-item:last-child' overwrites '.modal__menu-item:first-child'

**Comment by tiagodcosta** [comment]
Fixed with 8ec43a9fd0f4862952ec2ad3dbb4b310eff45d56
