### ISSUE TITLE
Give Memo notes the old computer css on customer issue screen

### ISSUE THREAD

**Issue by JSmith92** [inkdlab/writing-game-week3#7]
Give it the old css from email game. 
![screen shot 2017-01-19 at 2 13 24 pm](https://cloud.githubusercontent.com/assets/22644654/22121556/95ff2932-de52-11e6-9a81-215345e1388a.png)

**Comment by tiagodcosta** [comment]
Fixed with 3e578550f166fc39df776954fb3ec0a73fb3d9cb
