### ISSUE TITLE
Do we still need to go through these screens for intermediate and advanced now that we can't make phone calls? We go directly to the task for beginner

### ISSUE THREAD

**Issue by aarthyadityan** [inkdlab/writing-game-week3#8]
<img width="1234" alt="2017-01-19 02 35 39 pm" src="https://cloud.githubusercontent.com/assets/21074048/22122132/bf98f0dc-de54-11e6-8ec9-df6bdd90de75.png">
<img width="1238" alt="2017-01-19 02 35 49 pm" src="https://cloud.githubusercontent.com/assets/21074048/22122133/bfa01e7a-de54-11e6-812c-d266c0e7eeef.png">

**Comment by JSmith92** [comment]
I believe so. Julie gave us content for these screens, so just leave them in until they make their playthroughs.

**Comment by jaytay579** [comment]
Agreed. If we got content and it makes sense to have those screens in place, put them in. However, if there is a logical problem (i.e., the content refers to things that we have cut out) then please create an issue for me (Jay L) and Lori to resolve.

**Comment by aarthyadityan** [comment]
Ok, the content for the advanced one (which was referring to the phone calls) hadn't been updated yet, but that's fixed now
