### ISSUE TITLE
Create sectioned inputs for advanced assessment form

### ISSUE THREAD

**Issue by JSmith92** [inkdlab/writing-game-week3#9]
Section the inputs for the form

![screen shot 2017-01-19 at 2 48 06 pm](https://cloud.githubusercontent.com/assets/22644654/22122586/86b15398-de56-11e6-8bd1-c812579ec74f.png)

**Comment by aarthyadityan** [comment]
anyone working on this yet?

**Comment by JSmith92** [comment]
No. Go ahead if you plan on working on it.

**Comment by aarthyadityan** [comment]
Ok, I'll work on it then

**Comment by aarthyadityan** [comment]
I created the fields and linked them to the js. @tiagodcosta, can you help with the css

**Comment by tiagodcosta** [comment]
Yes I'll start to work on it

**Comment by tiagodcosta** [comment]
@aarthyadityan I added the new container for the memorandum. Could you add data to it?
![screen shot 2017-01-19 at 5 32 25 pm](https://cloud.githubusercontent.com/assets/19278068/22128265/bd0f8236-de6d-11e6-82eb-23ff14eae85c.png)

**Comment by aarthyadityan** [comment]
Yep, I'll do that
